---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  image: golang:1.17.3
  pull: always
  commands:
  - go vet ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: test
  image: golang:1.17.3
  pull: always
  commands:
  - go test -cover ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

trigger:
  ref:
  - refs/heads/master
  - refs/heads/edge-dind
  - refs/heads/feature-*
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: linux-amd64-docker

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  image: golang:1.17.3
  pull: always
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/drone-docker ./cmd/drone-docker"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  image: golang:1.17.3
  pull: always
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v}\" -a -tags netgo -o release/linux/amd64/drone-docker ./cmd/drone-docker"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  image: golang:1.17.3
  pull: always
  commands:
  - ./release/linux/amd64/drone-docker --help

- name: dryrun
  pull: always
  image: immawanderer/drone-docker:linux-amd64
  settings:
    daemon_off: true
    dockerfile: docker/docker/Dockerfile.linux.amd64
    dry_run: true
    repo: immawanderer/drone-docker
    tags: [linux-amd64, edge-dind]
  when:
    event: [push, pull_request]

- name: publish
  pull: always
  image: immawanderer/drone-docker:linux-amd64
  settings:
    daemon_off: false
    dockerfile: docker/docker/Dockerfile.linux.amd64
    tags:
      - latest
      - edge-dind
      - linux-amd64
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_SHA:0:8}-edge-dind
      - ${DRONE_COMMIT_SHA:0:8}-linux-amd64
    repo: immawanderer/drone-docker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [edge-dind]
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/heads/edge-dind
  - refs/heads/feature-*
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- testing

...
